language: node_js
node_js:
  - "0.10"
env: 
  global: 
    secure: CR0RYDzX5o+Jwd7wAE4XES8Gwpk6X9JbRREb7dFhfUgXoW1gLOlRlz5lI9CtXw4ib/XtYvm3gcpJADn63S+X2edVt5loQcB7wH8LhPYfdkhmDm+DUpugq4TZnWjkeYKkOQpu7l65dKCfO9nnXiuzZlJ4jIW7vhh3IPmHLUWUzAw=
before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
install:
  - sudo npm install -g yeoman
  - sudo npm install -g grunt-cli
  - sudo npm install bower-require
  - sudo gem install compass --version "=0.12.2"
script:
  - bower install
after_script:
  - ./bin/update-gh-pages.sh
